const UserActionTypes = {
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	CLEAR_USER_ERROR: 'CLEAR_USER_ERROR',
	SIGN_OUT: 'SIGN_OUT',
};

export default UserActionTypes;
